spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
cors:
  allowed-origins:
    - http://localhost:5173
    - capacitor://localhost
    - http://localhost
stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
jwt:
  secret: ${JWT_SECRET}