name: Deploy Lingoala Profile API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/implicationz/lingoala-profile-api:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/implicationz/lingoala-profile-api:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull ghcr.io/implicationz/lingoala-profile-api:latest
            
            echo "Stopping old container if running..."
            docker stop lingoala-profile-api || true
            docker rm lingoala-profile-api || true
            
            echo "Starting container with latest image..."
            docker run -d \
              --name lingoala-profile-api \
              --env-file /etc/lingoala/lingoala.env \
              --env-file /etc/lingoala/lingoala-profile-api.env \
              -p 8081:8080 \
              ghcr.io/implicationz/lingoala-profile-api:latest
            
            echo "Deployment finished."
